const express = require('express');
const pool = require('../db');
const router = express.Router();

function parseList(value){return String(value||'').split(',').map(s=>s.trim()).filter(Boolean);}
function timeToMinutes(v){if(!v)return null;const [h,m]=String(v).slice(0,5).split(':').map(Number);return h*60+m;}
function overlapMinutes(aStart,aEnd,bStart,bEnd){if([aStart,aEnd,bStart,bEnd].some(v=>v===null))return 0;return Math.max(0,Math.min(aEnd,bEnd)-Math.max(aStart,bStart));}
function haversineKm(lat1,lon1,lat2,lon2){if([lat1,lon1,lat2,lon2].some(v=>v===null||v===undefined||v===''||Number.isNaN(Number(v))))return null;const R=6371,p=Math.PI/180,dLat=(Number(lat2)-Number(lat1))*p,dLon=(Number(lon2)-Number(lon1))*p,a=Math.sin(dLat/2)**2+Math.cos(Number(lat1)*p)*Math.cos(Number(lat2)*p)*Math.sin(dLon/2)**2;return R*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a));}
function weekdayNow(tz='Asia/Seoul'){const name=new Intl.DateTimeFormat('en-US',{weekday:'short',timeZone:tz}).format(new Date());return ['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].indexOf(name)+1;}
function localNow(tz='Asia/Seoul'){const parts=new Intl.DateTimeFormat('en-GB',{weekday:'short',hour:'2-digit',minute:'2-digit',hour12:false,timeZone:tz}).formatToParts(new Date());const o=Object.fromEntries(parts.map(p=>[p.type,p.value]));return {weekday:['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].indexOf(o.weekday)+1,minutes:Number(o.hour)*60+Number(o.minute),time:`${o.hour}:${o.minute}`};}
function weatherBonus(category,kind){const cat=category||'';if(kind==='rain'||kind==='cold')return /국밥|찌개|탕|칼국수|우동|라멘|전골|설렁탕|감자탕/.test(cat)?18:0;if(kind==='hot')return /냉면|초밥|샐러드|국수|메밀|소바/.test(cat)?16:0;if(kind==='snow')return /국밥|탕|전골|라멘|우동|찌개/.test(cat)?20:0;return 0;}
function dayBonus(category,weekday){const cat=category||'';if(weekday===1&&/국밥|한식|찌개|설렁탕/.test(cat))return 4;if(weekday===5&&/고기|초밥|중식|치킨/.test(cat))return 4;return 0;}
function reasonPenalty(reason){const r=String(reason||'').toLowerCase();if(/비싸|가격|돈/.test(r))return {key:'price',value:22};if(/멀|거리|위치/.test(r))return {key:'distance',value:18};if(/대기|줄|혼잡/.test(r))return {key:'wait',value:18};if(/싫|맛|음식/.test(r))return {key:'food',value:25};return {key:'other',value:10};}

async function routeInfo(fromLat,fromLon,toLat,toLon){if(![fromLat,fromLon,toLat,toLon].every(Number.isFinite))return null;try{const url=`https://router.project-osrm.org/route/v1/foot/${fromLon},${fromLat};${toLon},${toLat}?overview=false&steps=false`;const r=await fetch(url,{signal:AbortSignal.timeout(5000)});if(!r.ok)return null;const d=await r.json();if(d.code!=='Ok'||!d.routes?.length)return null;return {distance_km:Number((d.routes[0].distance/1000).toFixed(2)),travel_minutes:Math.max(1,Math.round(d.routes[0].duration/60))};}catch{return null;}}

router.post('/today',async(req,res)=>{try{
  const userId=req.session.userId||null;let {city_id,area_id,budget_max=15000,people=2,weather='clear',weather_kind,latitude,longitude}=req.body;let pref=null;
  if(userId){const [p]=await pool.query('SELECT * FROM user_preferences WHERE user_id=? LIMIT 1',[userId]);if(p.length)pref=p[0];if(pref){city_id=city_id||pref.work_city_id;area_id=area_id||pref.work_area_id;budget_max=Number(pref.budget_max||budget_max);people=Number(pref.people||people);latitude=latitude??pref.latitude;longitude=longitude??pref.longitude;}}
  if(!city_id)return res.status(400).json({message:'근무 도시를 선택하거나 프로필에 저장하세요.'});
  const [cityRows]=await pool.query(`SELECT c.id,c.name,r.country_id,co.code country_code FROM cities c JOIN regions r ON r.id=c.region_id JOIN countries co ON co.id=r.country_id WHERE c.id=?`,[city_id]);
  if(!cityRows.length)return res.status(400).json({message:'도시 정보를 찾을 수 없습니다.'});
  const city=cityRows[0],tz=city.country_code==='JP'?'Asia/Tokyo':'Asia/Seoul',weekday=weekdayNow(tz),now=localNow(tz);const budget=Number(budget_max),persons=Number(people),lunchStart=timeToMinutes(pref?.lunch_start||'11:30:00'),lunchEnd=timeToMinutes(pref?.lunch_end||'13:30:00');
  let sql=`SELECT r.*,a.name area_name,c.code country_code,c.currency FROM restaurants r LEFT JOIN areas a ON a.id=r.area_id LEFT JOIN countries c ON c.id=r.country_id WHERE r.active=1 AND r.city_id=? AND r.price_max<=?`;const params=[city_id,budget];if(area_id){sql+=' AND r.area_id=?';params.push(area_id);}sql+=persons>1?' AND r.group_ok=1':' AND r.solo_ok=1';const [rows]=await pool.query(sql,params);if(!rows.length)return res.status(404).json({message:'기본 조건에 맞는 음식점이 없습니다.'});
  const recentByRestaurant=new Map(),categoryStats=new Map(),reasonStats=new Map(),dayCategoryStats=new Map();
  if(userId){const [history]=await pool.query(`SELECT restaurant_id,action,reject_reason,visit_date FROM lunch_history WHERE user_id=? AND visit_date>=DATE_SUB(CURDATE(),INTERVAL 90 DAY) ORDER BY created_at DESC`,[userId]);for(const h of history){const key=h.restaurant_id,item=recentByRestaurant.get(key)||{visited:0,rejected:0,lastVisited:null};if(h.action==='visited'||h.action==='accepted'){item.visited++;if(!item.lastVisited||new Date(h.visit_date)>new Date(item.lastVisited))item.lastVisited=h.visit_date;}if(h.action==='rejected')item.rejected++;recentByRestaurant.set(key,item);}const [cats]=await pool.query(`SELECT r.category,h.action,COUNT(*) count FROM lunch_history h JOIN restaurants r ON r.id=h.restaurant_id WHERE h.user_id=? AND h.visit_date>=DATE_SUB(CURDATE(),INTERVAL 90 DAY) GROUP BY r.category,h.action`,[userId]);for(const c of cats){const s=categoryStats.get(c.category)||{visited:0,rejected:0};if(c.action==='visited'||c.action==='accepted')s.visited+=c.count;if(c.action==='rejected')s.rejected+=c.count;categoryStats.set(c.category,s);}const [reasons]=await pool.query(`SELECT reject_reason,COUNT(*) count FROM lunch_history WHERE user_id=? AND action='rejected' AND reject_reason IS NOT NULL GROUP BY reject_reason`,[userId]);for(const r of reasons){const p=reasonPenalty(r.reject_reason);reasonStats.set(p.key,(reasonStats.get(p.key)||0)+r.count);}const [dc]=await pool.query(`SELECT DAYOFWEEK(visit_date) dow,r.category,COUNT(*) count FROM lunch_history h JOIN restaurants r ON r.id=h.restaurant_id WHERE h.user_id=? AND h.action='visited' AND h.visit_date>=DATE_SUB(CURDATE(),INTERVAL 90 DAY) GROUP BY DAYOFWEEK(visit_date),r.category`,[userId]);for(const d of dc)dayCategoryStats.set(`${d.dow}:${d.category}`,d.count);}
  const likedArr=parseList(pref?.liked_categories),dislikedArr=parseList(pref?.disliked_categories),todayWeatherKind=weather_kind||'clear',userLat=Number.isFinite(Number(latitude))?Number(latitude):null,userLon=Number.isFinite(Number(longitude))?Number(longitude):null;
  let scored=rows.map(r=>{const rs=timeToMinutes(r.lunch_start),re=timeToMinutes(r.lunch_end),bs=timeToMinutes(r.break_start),be=timeToMinutes(r.break_end),overlap=overlapMinutes(lunchStart,lunchEnd,rs,re),breakOverlap=overlapMinutes(lunchStart,lunchEnd,bs,be);if(overlap<Math.min(45,Number(r.meal_minutes||60))||breakOverlap>0)return null;const days=parseList(r.open_days||'1,2,3,4,5,6,7').map(Number);if(days.length&&!days.includes(weekday))return null;const distanceKm=haversineKm(userLat,userLon,r.latitude,r.longitude),recent=recentByRestaurant.get(r.id)||{visited:0,rejected:0,lastVisited:null},daysSince=recent.lastVisited?Math.max(0,Math.floor((Date.now()-new Date(recent.lastVisited).getTime())/86400000)):999,catStat=categoryStats.get(r.category)||{visited:0,rejected:0};let score=20;const reasons=['예산 범위 충족','점심시간과 영업시간 일치'];if(likedArr.some(x=>(r.category||'').includes(x))){score+=25;reasons.push('내가 좋아하는 음식');}if(dislikedArr.some(x=>(r.category||'').includes(x)))score-=100;if(recent.visited){const p=Math.max(8,25-Math.min(daysSince,14));score-=p;if(daysSince>=7)score+=6;}else{score+=15;reasons.push('최근 방문 기록 없음');}if(recent.rejected)score-=Math.min(42,recent.rejected*12);if(catStat.rejected)score-=Math.min(24,catStat.rejected*4);if(catStat.visited>catStat.rejected)score+=Math.min(12,catStat.visited*2);const wb=weatherBonus(r.category,todayWeatherKind);if(wb){score+=wb;reasons.push('오늘 날씨에 어울리는 메뉴');}score+=dayBonus(r.category,weekday);const wc=dayCategoryStats.get(`${weekday}:${r.category}`)||0;if(wc>=2)score-=Math.min(10,wc*2);if(distanceKm!==null)score+=Math.max(-10,12-distanceKm*4);else score-=2;if(reasonStats.get('price')&&Number(r.price_max)>budget*0.9)score-=Math.min(10,reasonStats.get('price')*2);if(reasonStats.get('distance')&&distanceKm!==null&&distanceKm>0.8)score-=Math.min(8,reasonStats.get('distance')*1.5);return {...r,distance_km:distanceKm===null?null:Number(distanceKm.toFixed(2)),score:Number(score.toFixed(2)),_reasons:reasons};}).filter(Boolean).filter(r=>!dislikedArr.some(x=>(r.category||'').includes(x))).sort((a,b)=>b.score-a.score);
  if(!scored.length)return res.status(404).json({message:'오늘 점심시간에 영업 가능한 음식점이 없습니다.'});
  // 실제 도보 이동시간을 상위 후보에 반영
  if(userLat!==null&&userLon!==null){for(const r of scored.slice(0,8)){const route=await routeInfo(userLat,userLon,Number(r.latitude),Number(r.longitude));if(route){r.route_distance_km=route.distance_km;r.travel_minutes=route.travel_minutes;r.score=Number((r.score+Math.max(-12,12-route.travel_minutes*0.6)).toFixed(2));r._reasons.push(`실제 도보 약 ${route.travel_minutes}분`);}}scored.sort((a,b)=>b.score-a.score);}
  // 현재 현지 영업 상태도 표시하고, 점심시간에 영업하지 않는 후보는 제외
  scored=scored.map(r=>{const t=localNow(r.country_code==='JP'?'Asia/Tokyo':'Asia/Seoul'),days=parseList(r.open_days||'1,2,3,4,5,6,7').map(Number),openDay=days.includes(t.weekday),s=timeToMinutes(r.lunch_start),e=timeToMinutes(r.lunch_end),bs=timeToMinutes(r.break_start),be=timeToMinutes(r.break_end),openNow=openDay&&s!==null&&e!==null&&t.minutes>=s&&t.minutes<e&&!(bs!==null&&be!==null&&t.minutes>=bs&&t.minutes<be);return {...r,open_now:openNow,local_time:t.time};});
  const winner=scored[0],reasons=winner._reasons.length?winner._reasons:['저장된 개인 조건과 상황을 종합 판단'];
  if(userId){const context={weather,weather_kind:todayWeatherKind,weekday,budget,people,distance_km:winner.route_distance_km??winner.distance_km,travel_minutes:winner.travel_minutes||null,local_time:winner.local_time,open_now:winner.open_now,score:winner.score};await pool.query(`INSERT INTO lunch_history(user_id,restaurant_id,visit_date,action,memo,context_json,decision_score,distance_km,weather_kind) VALUES(?,?,CURDATE(),'recommended',?,?,?, ?, ?)`,[userId,winner.id,'V6 자동 결정',JSON.stringify(context),winner.score,winner.route_distance_km??winner.distance_km,todayWeatherKind]);}
  res.json({winner,candidates:scored.slice(0,5),reasons,loggedIn:!!userId,context:{weather,weather_kind:todayWeatherKind,weekday,timezone:tz,localTime:now.time,liveRoute:!!winner.travel_minutes,liveOpening:winner.open_now}});
}catch(e){console.error(e);res.status(500).json({message:'자동 결정 중 서버 오류가 발생했습니다.',detail:e.message});}});

router.post('/feedback',async(req,res)=>{try{if(!req.session.userId)return res.status(401).json({message:'내 이력을 저장하려면 먼저 로그인하세요.'});const {restaurant_id,action,reject_reason='',memo=''}=req.body;if(!['visited','rejected'].includes(action))return res.status(400).json({message:'방문 또는 거부만 기록할 수 있습니다.'});await pool.query(`INSERT INTO lunch_history(user_id,restaurant_id,visit_date,action,reject_reason,memo) VALUES(?,?,CURDATE(),?,?,?)`,[req.session.userId,restaurant_id,action,reject_reason||null,memo||null]);res.json({ok:true});}catch(e){res.status(500).json({message:e.message});}});
module.exports=router;
